import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { GlobalProvider } from "../components/context/GlobalContext";
import AnnouncementBar from "../components/user/AnnouncementBar";
import Navbar from "../components/user/Navbar";
import Footer from "../components/user/Footer";
import CartSidebar from "../components/user/CartSidebar";
import LoginSignup from "../components/user/LoginSignup";
import Wishlist from '../components/user/Wishlist'
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import OrderSidebar from '../components/user/OrderSidebar'
import Icon from "../components/user/Icons";
import { GoogleOAuthProvider } from "@react-oauth/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Saajriwaaj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("Google ID:", process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID);

  return (
    <html lang="en">
 <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        {/* <link rel="icon" href="/favicon.png" type="image/png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" /> */}
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  `}
      >
        <GoogleOAuthProvider  clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID}>
        <GlobalProvider>
            <AnnouncementBar />
                <Navbar/>
                      <CartSidebar/>
                      <LoginSignup/>
                      <Wishlist/>
                      <OrderSidebar/>
                             
        {children}
<Icon/>
              <Footer />
        </GlobalProvider>
        <ToastContainer position="top-right" autoClose={3000} hideProgressBar />
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
